import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../../components/Header'

const Articles: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className='max-w-2xl m-auto'>

      <h1 className='text-3xl font-bold underline'>
        Articles
      </h1>
      <p>
        Toutes les Articless
      </p>


      </main>
      
    </div>
  )
}

export default Articles
