import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { ParsedUrlQuery } from "querystring";
import React, { useState } from "react";
import Footer from "../../components/Footer/Footer";
import Header from "../../components/Header";
import { sanityClient, urlFor } from "../../sanity";
import { IPost, IRecepies } from "../../types";

interface Props {
  recepie: IRecepies;
}

interface IParams extends ParsedUrlQuery {
  slug: string;
}

export const Post = ({ recepie }: Props) => {
  const [nbPerson, setNbPerson] = useState<number>(2);
  // console.log(recepie.mainImage.asset._ref.split('image-')[1])
  console.log(urlFor(recepie.mainImage).url());

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="my-16">
        <article>
          <section
            style={{
              backgroundImage:
                "linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0)), url(" +
                urlFor(recepie.mainImage).url() +
                ")",
            }}
            className={`relative h-48 bg-cover shadow-xl shadow-black" rounded-b-3xl`}
          >
            <h1 className="absolute text-2xl font-bold text-white bg-primary-color p-3 right-0 bottom-9 rounded-l-lg">
              {recepie.title}
            </h1>
          </section>
          <section className="px-5 mx-auto pt-5">
            <h2 className="text-xl font-bold mb-3">Temps de préparation</h2>
            <div className="p-5 rounded-xl shadow-gray-700/20 shadow-md">
              <div className="text-center pb-2">
                <span className="font-semibold text-gray-800">
                  Temps total:{" "}
                </span>
                {recepie?.duration.totalTime} min
              </div>
              <div className="flex justify-around">
                <div>
                  <h2 className="font-semibold text-gray-800">Préparation</h2>
                  <p className="text-center">
                    {recepie.duration.preparationTime
                      ? `${recepie.duration.preparationTime} min`
                      : "-"}
                  </p>
                </div>
                <div>
                  <h2 className="font-semibold text-gray-800">Repos</h2>
                  <p className="text-center">
                    {recepie?.duration.restTime
                      ? `${recepie?.duration.restTime} min`
                      : "-"}
                  </p>
                </div>
                <div>
                  <h2 className="font-semibold text-gray-800">Cuisson</h2>
                  <p className="text-center">
                    {recepie?.duration.cookTime
                      ? `${recepie?.duration.cookTime} min`
                      : "-"}
                  </p>
                </div>
              </div>
            </div>
          </section>
          <section className="px-5 pt-5">
            <h2 className="text-xl font-bold mb-3">Nombre de personnes</h2>
            <div className="flex justify-center p-5 rounded-xl shadow-gray-700/20 shadow-md">
              <div
                className=" bg-primary-color rounded-full w-7 h-7 flex justify-center items-center text-white text-2xl leading-none"
                onClick={() => {
                  if (nbPerson > 1) {
                    setNbPerson((prev) => prev - 1);
                  }
                }}
              >
                -
              </div>
              {nbPerson === 1 && <p className="mx-5">{nbPerson} personne</p>}
              {nbPerson > 1 && <p className="mx-5">{nbPerson} personnes</p>}

              <button
                className=" bg-primary-color rounded-full w-7 h-7 flex justify-center items-center text-white text-2xl leading-none"
                onClick={() => {
                  if (nbPerson < 20) {
                    setNbPerson((prev) => prev + 1);
                  }
                }}
              >
                +
              </button>
            </div>
          </section>
          <section className="px-5 pt-5">
            <h2 className="text-xl font-bold mb-3">Ingredients</h2>
            <div className="p-5 rounded-xl shadow-gray-700/20 shadow-md">
              <ul className="">
                {recepie.ingredients.map((ingredient, index) => (
                  <li className="list-inside" key={index}>
                    {"• "}
                    {ingredient.quantity * nbPerson} {ingredient.unit}{" "}
                    {ingredient.title}
                  </li>
                ))}
              </ul>
            </div>
          </section>
          <section className="px-5 pt-5">
            <h2 className="text-xl font-bold mb-3">Préparation</h2>
          </section>
        </article>
      </main>
      <Footer />
    </div>
  );
};

export default Post;

export const getStaticPaths = async () => {
  const query = `
  *[_type == 'recepies']{
    _createdAt,
    _id,
    _type,
    duration,
    ingredients,
    mainImage,
    title,
    type,
    slug
  }
  `;

  const recepies = await sanityClient.fetch(query);

  const paths: any = [];

  recepies.forEach((recepie: IRecepies) => {
    paths.push({ params: { slug: recepie.slug.current } });
  });

  return {
    paths: paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const { slug } = context.params as IParams;

  const query = `*[_type == 'recepies' && slug.current == $slug][0]{
    _createdAt,
    _id,
    _type,
    duration,
    ingredients,
    mainImage,
    title,
    type,
    slug
  }`;

  const recepie = await sanityClient.fetch(query, { slug: slug });

  if (!recepie) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      recepie,
    },
  };
};
