import Head from "next/head";
import Image from "next/image";
import React, { ReactElement } from "react";
import AboutPageLayout from "../../components/Layout/AboutPageLayout";
import type { NextPageWithLayout } from "../_app";

import profilePic from "./../../public/profile-pic.png";

const MePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>A propos | Moi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h2 className="text-3xl font-bold text-center py-7">Je me présente</h2>
        <p className="text-justify my-3 indent-6 lg:text-lg">
          Je m’appelle LANDEAU Fiona et suis diplômée d’un BTS diététique depuis
          2018. J’aime apprendre et c’est pourquoi j’ai également obtenu par la
          suite un Diplôme Universitaire en micronutrition et suis actuellement
          en cours de formation pour devenir sophrologue.{" "}
        </p>
        <Image src={profilePic} layout="responsive" />
        <p className="text-justify my-3 indent-6 lg:text-lg">
          Mon objectif premier est de vous permettre de retrouver plaisir de
          manger, grâce à des conseils personnalisés. En effet, mes compétences
          actuelles me permettent d’allier sophrologie et diététique, ce qui
          vous permettra de trouver une manière de vous nourrir simple et
          radicalement différente de vos habitudes : manger en pleine
          conscience.
        </p>
        <p className="text-justify my-3 indent-6 lg:text-lg">
          Ce mode d’alimentation en plein conscience s’adresse à tous, aussi
          bien les hommes que les femmes, les gros comme les petits mangeurs,
          adeptes ou non de régimes… Quelques idées d’objectifs :
        </p>
        <ul className="pl-7 lg:text-lg">
          <li>
            &bull; Vous proposez une alimentation équilibrée et de bonnes
            habitudes alimentaires : Et donc d’arrêter les régimes !
          </li>
          <li>
            &bull; Vous aidez à être à l’écoute de votre corps et donc de mieux
            respecter vos sensations alimentaires.
          </li>
          <li>
            &bull; D’accepter vos écarts et vos difficultés (propres à tout
            changement d’habitude) avec bienveillance, et le tout sans jugement.
          </li>
          <li>
            &bull; Et enfin de vous rendre proposer des outils qui vous
            accompagneront toute votre vie ; et donc, de devenir autonome d’un
            point de vue nutritionnel.{" "}
          </li>
        </ul>
        <p className="text-justify my-3 indent-6 lg:text-lg">
          Si ce programme vous plait, c’est avec plaisir que nous pourrons
          prendre contact afin d’envisager un suivi ensemble, à votre rythme
          pour développer une attitude positive face à la nourriture et envers
          vous-même pour enfin vous sentir bien dans votre assiette et dans
          votre corps.
        </p>
      </section>
    </>
  );
};

MePage.getLayout = function getLayout(page: ReactElement) {
  return <AboutPageLayout>{page}</AboutPageLayout>;
};

export default MePage;
