import Head from "next/head";
import React, { ReactElement } from "react";
import AboutPageLayout from "../../components/Layout/AboutPageLayout";
import type { NextPageWithLayout } from "../_app";

const SophroPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>A propos | Moi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h2 className="text-3xl font-bold text-center py-7">La Sophrologie</h2>
        <p className="text-justify my-3 indent-6 lg:text-lg">
          La sophrologie est une méthode psychocorporelle utilisée comme
          technique thérapeutique ou vécue comme une philosophie de vie. Elle a
          été conçue par le neuropsychiatre Alfonso Caycedo et est inspirée de
          techniques occidentales comme orientales. La sophrologie, c’est
          réussir à prendre conscience de l’ensemble des phénomènes qui se
          produisent à chaque instant au sein de notre corps sans que nous en
          ayons conscience.
        </p>
        <p className="text-justify my-3 indent-6 lg:text-lg">
          Pourquoi ANCLAJE ? de l'espagnol ancrage. L’espagnol, langue natale
          d'Alfonso Caycedo, fondateur de la sophrologie, né en Colombie en
          1932.
        </p>
        <p className="text-justify my-3 indent-6 lg:text-lg">
          “S’ancrer” dans son corps / Écouter son corps / Partir à la rencontre
          de soi-même.
        </p>
        <p className="text-justify my-3 indent-6 lg:text-lg">
          Être en pleine conscience, c'est développer une relation étroite avec
          son esprit. Manger en pleine conscience est une approche durable et
          vous permettra d’adopter des habitudes saines dont vous ne pourrez
          plus vous passer !
        </p>
        <p className="text-justify my-3 indent-6 lg:text-lg">
          Cet état permet d’accepter ce que vous pensez ou éprouvez sans
          jugement : cela vous permettra d’en connaître plus sur vous. Il s'allie à
          la perfection avec notre façon de nous alimenter. En effet, vous
          verrez par vous même qu’aucun aliment n’est interdit, tout est
          question d’équilibre. Prendre conscience de ses habitudes alimentaires
          vous permettra d’adapter votre alimentation en fonction de vos
          besoins. Cela vous changera des régimes alimentaires classiques :)
        </p>
      </section>
    </>
  );
};

SophroPage.getLayout = function getLayout(page: ReactElement) {
  return <AboutPageLayout>{page}</AboutPageLayout>;
};

export default SophroPage;
