import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='max-w-2xl m-auto'>

      <h1 className='text-3xl font-bold underline' >
        About page
      </h1>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel eligendi accusantium nihil sunt enim, quam cum provident ea recusandae officiis, aperiam eum quae saepe soluta! Error et eius numquam, excepturi enim nobis temporibus similique consequatur, non sunt eos unde placeat.
      </p>


      </main>
      
    </div>
  )
}

export default About
