import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../components/Header";

import profilePic from "./../public/profile-pic.jpg";

import listenIcon from './../public/listen-icon.png'
import confianceIcon from './../public/confiance-icon.png'
import followIcon from './../public/follow-icon.png'
import { useViewportScroll } from "framer-motion";
import { useEffect } from "react";



const Home: NextPage = () => {
  const {scrollYProgress} = useViewportScroll();

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mx-auto my-16">
        <section className="bg-presentation-section bg-cover bg-bottom py-20">
          <h1 className="w-fit m-auto text-4xl font-bold text-slate-50 pb-8 md:text-5xl lg:text-7xl">
            FIONA LANDEAU
          </h1>
          <h2 className="w-fit m-auto text-2xl text-slate-100 md:text-3xl lg:text-4xl">
            Nutritioniste - Sofrologue
          </h2>
        </section>
        <section className="px-5 py-5">
          <div className="">
            <h2 className="text-green-300 text-2xl font-bold mb-5">
              Qui-suis-je ?
            </h2>
            <Image src={profilePic} layout="responsive" />
            <p className="text-justify mt-5 indent-5">
              Je m’appelle LANDEAU Fiona et suis diplômée d’un BTS diététique
              depuis 2018. J’aime apprendre et c’est pourquoi j’ai également
              obtenu par la suite un Diplôme Universitaire en micronutrition et
              suis actuellement en cours de formation pour devenir sophrologue.
            </p>
            <p className="text-justify mt-3 mb-5 indent-5">
              Mon objectif premier est de vous permettre de retrouver plaisir de
              manger, grâce a des conseils personnalisés. En effet, mes
              compétences actuelles me permettent d’allier sophrologie et
              diététique, ce qui vous permettra de trouver une manière de vous
              nourrir simple et radicalement différente de vos habitudes :
              manger en pleine conscience.
            </p>
            <Link href="/about">
              <a className="block bg-green-300 text-white p-4 rounded-lg font-semibold w-fit m-auto">En Savoir Plus</a>
            </Link>
          </div>
        </section>
        <section className="bg-green-300 px-5 py-5">
          <h2 className="text-white text-2xl font-bold mb-5">
            Mes Valeurs
          </h2>
          <div>
            <div className="relative border-8 border-white my-16">
              <div className="origin-center absolute left-1/2 -translate-x-1/2 top-0 -translate-y-1/2  bg-white w-fit rounded-full p-6">
                <Image src={listenIcon} width={30} height={30}/>
              </div>
              <h3 className="text-white text-3xl w-fit mx-auto mt-12 font-semibold">A l'écoute</h3>
              <p className="p-5 text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae eius inventore sit earum, iure eveniet?</p>
            </div>
            <div className="relative border-8 border-white my-16">
              <div className="origin-center absolute left-1/2 -translate-x-1/2 top-0 -translate-y-1/2  bg-white w-fit rounded-full p-6">
                <Image src={confianceIcon} width={30} height={30}/>
              </div>
              <h3 className="text-white text-3xl w-fit mx-auto mt-12 font-semibold">Confiance</h3>
              <p className="p-5 text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae eius inventore sit earum, iure eveniet?</p>
            </div>
            <div className="relative border-8 border-white my-16">
              <div className="origin-center absolute left-1/2 -translate-x-1/2 top-0 -translate-y-1/2  bg-white w-fit rounded-full p-6">
                <Image src={followIcon} width={30} height={30}/>
              </div>
              <h3 className="text-white text-3xl w-fit mx-auto mt-12 font-semibold">Suivis</h3>
              <p className="p-5 text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae eius inventore sit earum, iure eveniet?</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
